/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/extensions/replace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Replace Extensions */
        get: operations["replace_extensions_api_v2_extensions_replace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/extensions/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Available
         * @description Get all available extensions from the configured repository.
         */
        get: operations["get_available_api_v2_extensions_available_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/extensions/installed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Installed
         * @description Get all currently installed extensions.
         */
        get: operations["get_installed_api_v2_extensions_installed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/extensions/repository": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Repository
         * @description Update the extension repository URL.
         *
         *     Returns the list of available extensions from the new repository.
         */
        put: operations["update_repository_api_v2_extensions_repository_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/extensions/install/{extension_pkg}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Install Extension
         * @description Install an extension by package name.
         */
        post: operations["install_extension_api_v2_extensions_install__extension_pkg__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/extensions/uninstall/{extension_pkg}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Uninstall Extension
         * @description Uninstall an extension by package name.
         */
        delete: operations["uninstall_extension_api_v2_extensions_uninstall__extension_pkg__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/extensions/priority": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Extensions Priority
         * @description Update an extension's priority.
         */
        put: operations["update_extensions_priority_api_v2_extensions_priority_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/extensions/{extension_pkg}/proxy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Toggle Extension Proxy
         * @description Enable or disable proxy mode for an extension.
         */
        put: operations["toggle_extension_proxy_api_v2_extensions__extension_pkg__proxy_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/extensions/source/{source_id}/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Source Preferences
         * @description Get available preferences for source.
         */
        get: operations["get_source_preferences_api_v2_extensions_source__source_id__preferences_get"];
        /**
         * Update Source Preferences
         * @description Update source preferences
         */
        put: operations["update_source_preferences_api_v2_extensions_source__source_id__preferences_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/extensions/source/{source_id}/enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Toggle Source
         * @description Enable or disable a source.
         */
        put: operations["toggle_source_api_v2_extensions_source__source_id__enabled_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/discover/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Latest Titles */
        get: operations["list_latest_titles_api_v2_discover_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Simple health check endpoint suitable for readiness probes.
         */
        get: operations["health_check_api_v2_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ExtensionResource */
        ExtensionResource: {
            /** Pkg */
            pkg: string;
            /** Name */
            name: string;
            /** Lang */
            lang: string;
            /** Version */
            version: string;
            /** Nsfw */
            nsfw: boolean;
            /** Sources Has Prefs */
            sources_has_prefs: boolean;
            /** Icon */
            icon: string;
            /** Priority */
            priority: number;
            /** Installed */
            installed: boolean;
            /** Use Proxy */
            use_proxy: boolean;
            /** Sources */
            sources: components["schemas"]["Source"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PreferenceType
         * @enum {string}
         */
        PreferenceType: "list" | "toggle" | "multi_select" | "text";
        /** RepoExtensionResource */
        RepoExtensionResource: {
            /** Pkg */
            pkg: string;
            /** Name */
            name: string;
            /** Lang */
            lang: string;
            /** Version */
            version: string;
            /** Nsfw */
            nsfw: boolean;
            /** Sources Has Prefs */
            sources_has_prefs: boolean;
            /** Icon */
            icon: string;
            /** Installed */
            installed: boolean;
        };
        /** RepositoryUpdate */
        RepositoryUpdate: {
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** Source */
        Source: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Lang */
            lang: string;
            /** Base Url */
            base_url?: string | null;
            /** Supports Latest */
            supports_latest: boolean | null;
            /** Extension Pkg */
            extension_pkg: string;
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
        };
        /** SourcePreference */
        SourcePreference: {
            /** Key */
            key: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string | null;
            type: components["schemas"]["PreferenceType"];
            /** Enabled */
            enabled: boolean;
            /** Visible */
            visible: boolean;
            /** Default Value */
            default_value?: unknown | null;
            /** Current Value */
            current_value?: unknown | null;
            /** Entries */
            entries?: string[] | null;
            /** Entry Values */
            entry_values?: string[] | null;
            /** Dialog Title */
            dialog_title?: string | null;
            /** Dialog Message */
            dialog_message?: string | null;
        };
        /** SourcePreferencesResource */
        SourcePreferencesResource: {
            /** Source Id */
            source_id: string;
            /** Name */
            name: string;
            /** Lang */
            lang: string;
            /** Preferences */
            preferences: components["schemas"]["SourcePreference"][];
        };
        /** SourceTitle */
        SourceTitle: {
            /** Url */
            url: string;
            /** Title */
            title: string;
            status: components["schemas"]["Status"];
            /** Thumbnail Url */
            thumbnail_url: string;
            /** Artist */
            artist: string | null;
            /** Author */
            author: string | null;
            /** Description */
            description: string | null;
            /** Genre */
            genre: string | null;
            /** Source Id */
            source_id: number;
        };
        /**
         * Status
         * @enum {integer}
         */
        Status: 0 | 1 | 2 | 3 | 4 | 5 | 6;
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    replace_extensions_api_v2_extensions_replace_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepoExtensionResource"][];
                };
            };
        };
    };
    get_available_api_v2_extensions_available_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepoExtensionResource"][];
                };
            };
        };
    };
    get_installed_api_v2_extensions_installed_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtensionResource"][];
                };
            };
        };
    };
    update_repository_api_v2_extensions_repository_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepositoryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepoExtensionResource"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    install_extension_api_v2_extensions_install__extension_pkg__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                extension_pkg: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtensionResource"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    uninstall_extension_api_v2_extensions_uninstall__extension_pkg__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                extension_pkg: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_extensions_priority_api_v2_extensions_priority_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_extension_proxy_api_v2_extensions__extension_pkg__proxy_put: {
        parameters: {
            query: {
                use_proxy: boolean;
            };
            header?: never;
            path: {
                extension_pkg: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_preferences_api_v2_extensions_source__source_id__preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcePreferencesResource"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_source_preferences_api_v2_extensions_source__source_id__preferences_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourcePreference"][];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_source_api_v2_extensions_source__source_id__enabled_put: {
        parameters: {
            query: {
                enabled: boolean;
            };
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_latest_titles_api_v2_discover_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceTitle"][];
                };
            };
        };
    };
    health_check_api_v2_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
