services:
  mangarr:
    image: ghcr.io/tftiwnbe/mangarr:latest
    environment:
      - MANGARR_PUBLIC_URL=https://mangarr.hmphin.space
    ports:
      - "3737:3737"
    volumes:
      - ./config:/app/config
      - ./data:/app/downloads
    restart: unless-stopped
