"""initial_schema

Revision ID: 000_initial
Revises: 
Create Date: 2026-03-08 06:50:26.620644

"""
from collections.abc import Sequence
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "000_initial"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _seed_default_library_collections() -> None:
    now = datetime.now(timezone.utc)
    collections = sa.table(
        "library_collections",
        sa.column("name", sa.String()),
        sa.column("description", sa.String()),
        sa.column("color", sa.String()),
        sa.column("position", sa.Integer()),
        sa.column("created_at", sa.DateTime()),
        sa.column("updated_at", sa.DateTime()),
    )
    op.bulk_insert(
        collections,
        [
            {
                "name": "Favorites",
                "description": "Top picks",
                "color": "#71717a",
                "position": 1,
                "created_at": now,
                "updated_at": now,
            },
            {
                "name": "Queue",
                "description": "Read next",
                "color": "#71717a",
                "position": 2,
                "created_at": now,
                "updated_at": now,
            },
            {
                "name": "Archive",
                "description": "Saved for later",
                "color": "#71717a",
                "position": 3,
                "created_at": now,
                "updated_at": now,
            },
        ],
    )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discover_cache_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('dedupe_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artist', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('genre', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section', 'source_id', 'page', 'rank', name='uq_discover_cache_items_rank')
    )
    op.create_index(op.f('ix_discover_cache_items_dedupe_key'), 'discover_cache_items', ['dedupe_key'], unique=False)
    op.create_index(op.f('ix_discover_cache_items_page'), 'discover_cache_items', ['page'], unique=False)
    op.create_index(op.f('ix_discover_cache_items_section'), 'discover_cache_items', ['section'], unique=False)
    op.create_index(op.f('ix_discover_cache_items_source_id'), 'discover_cache_items', ['source_id'], unique=False)
    op.create_table('discover_cache_pages',
    sa.Column('section', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('has_next_page', sa.Boolean(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('section', 'source_id', 'page')
    )
    op.create_table('download_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_title_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('auto_download', sa.Boolean(), nullable=False),
    sa.Column('strategy', sa.Enum('NEW_ONLY', 'ALL_UNREAD', name='downloadstrategy'), nullable=False),
    sa.Column('preferred_variant_id', sa.Integer(), nullable=True),
    sa.Column('variant_ids_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_from', sa.DateTime(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('library_title_id', name='uq_download_profile_title')
    )
    op.create_index(op.f('ix_download_profiles_enabled'), 'download_profiles', ['enabled'], unique=False)
    op.create_index(op.f('ix_download_profiles_library_title_id'), 'download_profiles', ['library_title_id'], unique=False)
    op.create_index(op.f('ix_download_profiles_paused'), 'download_profiles', ['paused'], unique=False)
    op.create_index(op.f('ix_download_profiles_preferred_variant_id'), 'download_profiles', ['preferred_variant_id'], unique=False)
    op.create_table('download_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_title_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chapter_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chapter_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempt_group_id', sa.Integer(), nullable=True),
    sa.Column('retry_of_task_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'DOWNLOADING', 'COMPLETED', 'FAILED', 'CANCELLED', name='downloadtaskstatus'), nullable=False),
    sa.Column('trigger', sa.Enum('MONITOR', 'MANUAL', name='downloadtrigger'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(), nullable=False),
    sa.Column('downloaded_pages', sa.Integer(), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('output_dir', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_tasks_attempt_group_id'), 'download_tasks', ['attempt_group_id'], unique=False)
    op.create_index(op.f('ix_download_tasks_available_at'), 'download_tasks', ['available_at'], unique=False)
    op.create_index(op.f('ix_download_tasks_chapter_id'), 'download_tasks', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_download_tasks_library_title_id'), 'download_tasks', ['library_title_id'], unique=False)
    op.create_index(op.f('ix_download_tasks_priority'), 'download_tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_download_tasks_retry_of_task_id'), 'download_tasks', ['retry_of_task_id'], unique=False)
    op.create_index(op.f('ix_download_tasks_source_id'), 'download_tasks', ['source_id'], unique=False)
    op.create_index(op.f('ix_download_tasks_status'), 'download_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_download_tasks_variant_id'), 'download_tasks', ['variant_id'], unique=False)
    op.create_table('explore_title_details_cache',
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artist', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('genre', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('source_id', 'title_url')
    )
    op.create_table('extensions',
    sa.Column('pkg', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lang', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nsfw', sa.Boolean(), nullable=False),
    sa.Column('sources_has_prefs', sa.Boolean(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('installed', sa.Boolean(), nullable=False),
    sa.Column('use_proxy', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('pkg')
    )
    op.create_table('library_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_library_collections_name'), 'library_collections', ['name'], unique=True)
    op.create_table('library_titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('local_cover_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('artist', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('genre', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('preferred_variant_id', sa.Integer(), nullable=True),
    sa.Column('user_status_id', sa.Integer(), nullable=True),
    sa.Column('user_rating', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_library_titles_canonical_key'), 'library_titles', ['canonical_key'], unique=False)
    op.create_index(op.f('ix_library_titles_preferred_variant_id'), 'library_titles', ['preferred_variant_id'], unique=False)
    op.create_index(op.f('ix_library_titles_user_status_id'), 'library_titles', ['user_status_id'], unique=False)
    op.create_table('library_user_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_library_user_statuses_key'), 'library_user_statuses', ['key'], unique=True)
    op.create_table('persistent_cache',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), server_default=sa.text('(NULL)'), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_persistent_cache_expires_at'), 'persistent_cache', ['expires_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_key_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_api_key_rotated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_api_key_hash'), 'users', ['api_key_hash'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_token_hash'), 'auth_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('download_profile_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['download_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'variant_id', name='uq_download_profile_variant')
    )
    op.create_index(op.f('ix_download_profile_variants_position'), 'download_profile_variants', ['position'], unique=False)
    op.create_index(op.f('ix_download_profile_variants_profile_id'), 'download_profile_variants', ['profile_id'], unique=False)
    op.create_index(op.f('ix_download_profile_variants_variant_id'), 'download_profile_variants', ['variant_id'], unique=False)
    op.create_table('integration_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_api_keys_key_hash'), 'integration_api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_integration_api_keys_user_id'), 'integration_api_keys', ['user_id'], unique=False)
    op.create_table('library_collection_titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('library_title_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['library_collections.id'], ),
    sa.ForeignKeyConstraint(['library_title_id'], ['library_titles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'library_title_id', name='uq_collection_title')
    )
    op.create_index(op.f('ix_library_collection_titles_collection_id'), 'library_collection_titles', ['collection_id'], unique=False)
    op.create_index(op.f('ix_library_collection_titles_library_title_id'), 'library_collection_titles', ['library_title_id'], unique=False)
    op.create_table('library_title_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_title_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_lang', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('artist', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('genre', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['library_title_id'], ['library_titles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'title_url', name='uq_library_variant_source_title')
    )
    op.create_index(op.f('ix_library_title_variants_library_title_id'), 'library_title_variants', ['library_title_id'], unique=False)
    op.create_index(op.f('ix_library_title_variants_source_id'), 'library_title_variants', ['source_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lang', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('supports_latest', sa.Boolean(), nullable=True),
    sa.Column('extension_pkg', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['extension_pkg'], ['extensions.pkg'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library_chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_title_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('chapter_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chapter_number', sa.Float(), nullable=False),
    sa.Column('scanlator', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_upload', sa.DateTime(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_downloaded', sa.Boolean(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('download_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('download_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reader_page_index', sa.Integer(), nullable=True),
    sa.Column('reader_comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reader_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['library_title_id'], ['library_titles.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['library_title_variants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id', 'chapter_url', name='uq_library_chapter_variant_url')
    )
    op.create_index(op.f('ix_library_chapters_is_downloaded'), 'library_chapters', ['is_downloaded'], unique=False)
    op.create_index(op.f('ix_library_chapters_is_read'), 'library_chapters', ['is_read'], unique=False)
    op.create_index(op.f('ix_library_chapters_library_title_id'), 'library_chapters', ['library_title_id'], unique=False)
    op.create_index(op.f('ix_library_chapters_reader_page_index'), 'library_chapters', ['reader_page_index'], unique=False)
    op.create_index(op.f('ix_library_chapters_variant_id'), 'library_chapters', ['variant_id'], unique=False)
    op.create_table('library_chapter_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('page_index', sa.Integer(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['library_chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_library_chapter_comments_chapter_id'), 'library_chapter_comments', ['chapter_id'], unique=False)
    op.create_table('library_chapter_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('page_index', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('local_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('local_size', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['library_chapters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id', 'page_index', name='uq_library_page_chapter_index')
    )
    op.create_index(op.f('ix_library_chapter_pages_chapter_id'), 'library_chapter_pages', ['chapter_id'], unique=False)
    _seed_default_library_collections()
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_library_chapter_pages_chapter_id'), table_name='library_chapter_pages')
    op.drop_table('library_chapter_pages')
    op.drop_index(op.f('ix_library_chapter_comments_chapter_id'), table_name='library_chapter_comments')
    op.drop_table('library_chapter_comments')
    op.drop_index(op.f('ix_library_chapters_variant_id'), table_name='library_chapters')
    op.drop_index(op.f('ix_library_chapters_reader_page_index'), table_name='library_chapters')
    op.drop_index(op.f('ix_library_chapters_library_title_id'), table_name='library_chapters')
    op.drop_index(op.f('ix_library_chapters_is_read'), table_name='library_chapters')
    op.drop_index(op.f('ix_library_chapters_is_downloaded'), table_name='library_chapters')
    op.drop_table('library_chapters')
    op.drop_table('sources')
    op.drop_index(op.f('ix_library_title_variants_source_id'), table_name='library_title_variants')
    op.drop_index(op.f('ix_library_title_variants_library_title_id'), table_name='library_title_variants')
    op.drop_table('library_title_variants')
    op.drop_index(op.f('ix_library_collection_titles_library_title_id'), table_name='library_collection_titles')
    op.drop_index(op.f('ix_library_collection_titles_collection_id'), table_name='library_collection_titles')
    op.drop_table('library_collection_titles')
    op.drop_index(op.f('ix_integration_api_keys_user_id'), table_name='integration_api_keys')
    op.drop_index(op.f('ix_integration_api_keys_key_hash'), table_name='integration_api_keys')
    op.drop_table('integration_api_keys')
    op.drop_index(op.f('ix_download_profile_variants_variant_id'), table_name='download_profile_variants')
    op.drop_index(op.f('ix_download_profile_variants_profile_id'), table_name='download_profile_variants')
    op.drop_index(op.f('ix_download_profile_variants_position'), table_name='download_profile_variants')
    op.drop_table('download_profile_variants')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_token_hash'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_api_key_hash'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_persistent_cache_expires_at'), table_name='persistent_cache')
    op.drop_table('persistent_cache')
    op.drop_index(op.f('ix_library_user_statuses_key'), table_name='library_user_statuses')
    op.drop_table('library_user_statuses')
    op.drop_index(op.f('ix_library_titles_user_status_id'), table_name='library_titles')
    op.drop_index(op.f('ix_library_titles_preferred_variant_id'), table_name='library_titles')
    op.drop_index(op.f('ix_library_titles_canonical_key'), table_name='library_titles')
    op.drop_table('library_titles')
    op.drop_index(op.f('ix_library_collections_name'), table_name='library_collections')
    op.drop_table('library_collections')
    op.drop_table('extensions')
    op.drop_table('explore_title_details_cache')
    op.drop_index(op.f('ix_download_tasks_variant_id'), table_name='download_tasks')
    op.drop_index(op.f('ix_download_tasks_status'), table_name='download_tasks')
    op.drop_index(op.f('ix_download_tasks_source_id'), table_name='download_tasks')
    op.drop_index(op.f('ix_download_tasks_retry_of_task_id'), table_name='download_tasks')
    op.drop_index(op.f('ix_download_tasks_priority'), table_name='download_tasks')
    op.drop_index(op.f('ix_download_tasks_library_title_id'), table_name='download_tasks')
    op.drop_index(op.f('ix_download_tasks_chapter_id'), table_name='download_tasks')
    op.drop_index(op.f('ix_download_tasks_available_at'), table_name='download_tasks')
    op.drop_index(op.f('ix_download_tasks_attempt_group_id'), table_name='download_tasks')
    op.drop_table('download_tasks')
    op.drop_index(op.f('ix_download_profiles_preferred_variant_id'), table_name='download_profiles')
    op.drop_index(op.f('ix_download_profiles_paused'), table_name='download_profiles')
    op.drop_index(op.f('ix_download_profiles_library_title_id'), table_name='download_profiles')
    op.drop_index(op.f('ix_download_profiles_enabled'), table_name='download_profiles')
    op.drop_table('download_profiles')
    op.drop_table('discover_cache_pages')
    op.drop_index(op.f('ix_discover_cache_items_source_id'), table_name='discover_cache_items')
    op.drop_index(op.f('ix_discover_cache_items_section'), table_name='discover_cache_items')
    op.drop_index(op.f('ix_discover_cache_items_page'), table_name='discover_cache_items')
    op.drop_index(op.f('ix_discover_cache_items_dedupe_key'), table_name='discover_cache_items')
    op.drop_table('discover_cache_items')
    # ### end Alembic commands ###
