"""empty message

Revision ID: b223ac982e55
Revises: 
Create Date: 2025-11-28 21:28:02.550586

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b223ac982e55'
down_revision: str | Sequence[str] |  None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_title',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extensions',
    sa.Column('pkg', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lang', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nsfw', sa.Boolean(), nullable=False),
    sa.Column('sources_has_prefs', sa.Boolean(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('installed', sa.Boolean(), nullable=False),
    sa.Column('use_proxy', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('pkg')
    )
    op.create_table('fetched_pages',
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('section', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('title_count', sa.Integer(), nullable=False),
    sa.Column('has_next_page', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('source_id', 'section', 'page')
    )
    op.create_table('persistent_cache',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), server_default=sa.text('(NULL)'), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_persistent_cache_expires_at'), 'persistent_cache', ['expires_at'], unique=False)
    op.create_table('sources',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lang', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('supports_latest', sa.Boolean(), nullable=True),
    sa.Column('extension_pkg', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['extension_pkg'], ['extensions.pkg'], ),
    sa.PrimaryKeyConstraint('id', 'extension_pkg')
    )
    op.create_table('source_titles',
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('UNKNOWN', 'ONGOING', 'COMPLETED', 'LICENSED', 'PUBLISHING_FINISHED', 'CANCELLED', 'ON_HIATUS', name='status'), nullable=False),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artist', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('genre', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('canonical_title_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_title_id'], ['canonical_title.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_titles')
    op.drop_table('sources')
    op.drop_index(op.f('ix_persistent_cache_expires_at'), table_name='persistent_cache')
    op.drop_table('persistent_cache')
    op.drop_table('fetched_pages')
    op.drop_table('extensions')
    op.drop_table('canonical_title')
    # ### end Alembic commands ###
