# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from .config import config_pb2 as mangarr_dot_tachibridge_dot_config_dot_config__pb2
from .extensions import (
    extensions_pb2 as mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2,
)
from . import tachibridge_pb2 as mangarr_dot_tachibridge_dot_tachibridge__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in mangarr/tachibridge/tachibridge_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class TachibridgeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetRepoUrl = channel.unary_unary(
            "/mangarr.tachibridge.Tachibridge/SetRepoUrl",
            request_serializer=mangarr_dot_tachibridge_dot_config_dot_config__pb2.SetRepoUrlRequest.SerializeToString,
            response_deserializer=mangarr_dot_tachibridge_dot_config_dot_config__pb2.SetRepoUrlResponse.FromString,
            _registered_method=True,
        )
        self.GetFlareSolverrConfig = channel.unary_unary(
            "/mangarr.tachibridge.Tachibridge/GetFlareSolverrConfig",
            request_serializer=mangarr_dot_tachibridge_dot_config_dot_config__pb2.GetFlareSolverrConfigRequest.SerializeToString,
            response_deserializer=mangarr_dot_tachibridge_dot_config_dot_config__pb2.GetFlareSolverrConfigResponse.FromString,
            _registered_method=True,
        )
        self.SetFlareSolverrConfig = channel.unary_unary(
            "/mangarr.tachibridge.Tachibridge/SetFlareSolverrConfig",
            request_serializer=mangarr_dot_tachibridge_dot_config_dot_config__pb2.SetFlareSolverrConfigRequest.SerializeToString,
            response_deserializer=mangarr_dot_tachibridge_dot_config_dot_config__pb2.SetFlareSolverrConfigResponse.FromString,
            _registered_method=True,
        )
        self.InstallExtension = channel.unary_unary(
            "/mangarr.tachibridge.Tachibridge/InstallExtension",
            request_serializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.InstallExtensionRequest.SerializeToString,
            response_deserializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.InstallExtensionResponse.FromString,
            _registered_method=True,
        )
        self.UninstallExtension = channel.unary_unary(
            "/mangarr.tachibridge.Tachibridge/UninstallExtension",
            request_serializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.UninstallExtensionRequest.SerializeToString,
            response_deserializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.UninstallExtensionResponse.FromString,
            _registered_method=True,
        )
        self.UpdateExtension = channel.unary_unary(
            "/mangarr.tachibridge.Tachibridge/UpdateExtension",
            request_serializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.UpdateExtensionRequest.SerializeToString,
            response_deserializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.InstallExtensionResponse.FromString,
            _registered_method=True,
        )
        self.ListRepoExtensions = channel.unary_unary(
            "/mangarr.tachibridge.Tachibridge/ListRepoExtensions",
            request_serializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.ListRepoExtensionsRequest.SerializeToString,
            response_deserializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.ListRepoExtensionsResponse.FromString,
            _registered_method=True,
        )
        self.ListSources = channel.unary_unary(
            "/mangarr.tachibridge.Tachibridge/ListSources",
            request_serializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.ListSourcesRequest.SerializeToString,
            response_deserializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.ListSourcesResponse.FromString,
            _registered_method=True,
        )
        self.SearchTitle = channel.unary_unary(
            "/mangarr.tachibridge.Tachibridge/SearchTitle",
            request_serializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.SearchTitleRequest.SerializeToString,
            response_deserializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.TitlesPageResponse.FromString,
            _registered_method=True,
        )
        self.GetPopularTitles = channel.unary_unary(
            "/mangarr.tachibridge.Tachibridge/GetPopularTitles",
            request_serializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.GetPopularTitlesRequest.SerializeToString,
            response_deserializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.TitlesPageResponse.FromString,
            _registered_method=True,
        )
        self.GetLatestTitles = channel.unary_unary(
            "/mangarr.tachibridge.Tachibridge/GetLatestTitles",
            request_serializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.GetLatestTitlesRequest.SerializeToString,
            response_deserializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.TitlesPageResponse.FromString,
            _registered_method=True,
        )
        self.GetTitleDetails = channel.unary_unary(
            "/mangarr.tachibridge.Tachibridge/GetTitleDetails",
            request_serializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.GetTitleDetailsRequest.SerializeToString,
            response_deserializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.TitleResponse.FromString,
            _registered_method=True,
        )
        self.GetChapterList = channel.unary_unary(
            "/mangarr.tachibridge.Tachibridge/GetChapterList",
            request_serializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.GetChaptersListRequest.SerializeToString,
            response_deserializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.ChaptersListResponse.FromString,
            _registered_method=True,
        )
        self.GetPageList = channel.unary_unary(
            "/mangarr.tachibridge.Tachibridge/GetPageList",
            request_serializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.GetPagesListRequest.SerializeToString,
            response_deserializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.PagesListResponse.FromString,
            _registered_method=True,
        )
        self.GetFilters = channel.unary_unary(
            "/mangarr.tachibridge.Tachibridge/GetFilters",
            request_serializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.GetFiltersRequest.SerializeToString,
            response_deserializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.FiltersResponse.FromString,
            _registered_method=True,
        )
        self.SetPreference = channel.unary_unary(
            "/mangarr.tachibridge.Tachibridge/SetPreference",
            request_serializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.SetPreferenceRequest.SerializeToString,
            response_deserializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.SetPreferenceResponse.FromString,
            _registered_method=True,
        )
        self.HealthCheck = channel.unary_unary(
            "/mangarr.tachibridge.Tachibridge/HealthCheck",
            request_serializer=mangarr_dot_tachibridge_dot_tachibridge__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=mangarr_dot_tachibridge_dot_tachibridge__pb2.HealthCheckResponse.FromString,
            _registered_method=True,
        )


class TachibridgeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetRepoUrl(self, request, context):
        """Configuration"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetFlareSolverrConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SetFlareSolverrConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def InstallExtension(self, request, context):
        """Extension management"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UninstallExtension(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateExtension(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListRepoExtensions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListSources(self, request, context):
        """Source operations (all now in extensions.proto package)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SearchTitle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetPopularTitles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetLatestTitles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetTitleDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetChapterList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetPageList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetFilters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SetPreference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """Health check"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_TachibridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "SetRepoUrl": grpc.unary_unary_rpc_method_handler(
            servicer.SetRepoUrl,
            request_deserializer=mangarr_dot_tachibridge_dot_config_dot_config__pb2.SetRepoUrlRequest.FromString,
            response_serializer=mangarr_dot_tachibridge_dot_config_dot_config__pb2.SetRepoUrlResponse.SerializeToString,
        ),
        "GetFlareSolverrConfig": grpc.unary_unary_rpc_method_handler(
            servicer.GetFlareSolverrConfig,
            request_deserializer=mangarr_dot_tachibridge_dot_config_dot_config__pb2.GetFlareSolverrConfigRequest.FromString,
            response_serializer=mangarr_dot_tachibridge_dot_config_dot_config__pb2.GetFlareSolverrConfigResponse.SerializeToString,
        ),
        "SetFlareSolverrConfig": grpc.unary_unary_rpc_method_handler(
            servicer.SetFlareSolverrConfig,
            request_deserializer=mangarr_dot_tachibridge_dot_config_dot_config__pb2.SetFlareSolverrConfigRequest.FromString,
            response_serializer=mangarr_dot_tachibridge_dot_config_dot_config__pb2.SetFlareSolverrConfigResponse.SerializeToString,
        ),
        "InstallExtension": grpc.unary_unary_rpc_method_handler(
            servicer.InstallExtension,
            request_deserializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.InstallExtensionRequest.FromString,
            response_serializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.InstallExtensionResponse.SerializeToString,
        ),
        "UninstallExtension": grpc.unary_unary_rpc_method_handler(
            servicer.UninstallExtension,
            request_deserializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.UninstallExtensionRequest.FromString,
            response_serializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.UninstallExtensionResponse.SerializeToString,
        ),
        "UpdateExtension": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateExtension,
            request_deserializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.UpdateExtensionRequest.FromString,
            response_serializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.InstallExtensionResponse.SerializeToString,
        ),
        "ListRepoExtensions": grpc.unary_unary_rpc_method_handler(
            servicer.ListRepoExtensions,
            request_deserializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.ListRepoExtensionsRequest.FromString,
            response_serializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.ListRepoExtensionsResponse.SerializeToString,
        ),
        "ListSources": grpc.unary_unary_rpc_method_handler(
            servicer.ListSources,
            request_deserializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.ListSourcesRequest.FromString,
            response_serializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.ListSourcesResponse.SerializeToString,
        ),
        "SearchTitle": grpc.unary_unary_rpc_method_handler(
            servicer.SearchTitle,
            request_deserializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.SearchTitleRequest.FromString,
            response_serializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.TitlesPageResponse.SerializeToString,
        ),
        "GetPopularTitles": grpc.unary_unary_rpc_method_handler(
            servicer.GetPopularTitles,
            request_deserializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.GetPopularTitlesRequest.FromString,
            response_serializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.TitlesPageResponse.SerializeToString,
        ),
        "GetLatestTitles": grpc.unary_unary_rpc_method_handler(
            servicer.GetLatestTitles,
            request_deserializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.GetLatestTitlesRequest.FromString,
            response_serializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.TitlesPageResponse.SerializeToString,
        ),
        "GetTitleDetails": grpc.unary_unary_rpc_method_handler(
            servicer.GetTitleDetails,
            request_deserializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.GetTitleDetailsRequest.FromString,
            response_serializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.TitleResponse.SerializeToString,
        ),
        "GetChapterList": grpc.unary_unary_rpc_method_handler(
            servicer.GetChapterList,
            request_deserializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.GetChaptersListRequest.FromString,
            response_serializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.ChaptersListResponse.SerializeToString,
        ),
        "GetPageList": grpc.unary_unary_rpc_method_handler(
            servicer.GetPageList,
            request_deserializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.GetPagesListRequest.FromString,
            response_serializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.PagesListResponse.SerializeToString,
        ),
        "GetFilters": grpc.unary_unary_rpc_method_handler(
            servicer.GetFilters,
            request_deserializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.GetFiltersRequest.FromString,
            response_serializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.FiltersResponse.SerializeToString,
        ),
        "SetPreference": grpc.unary_unary_rpc_method_handler(
            servicer.SetPreference,
            request_deserializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.SetPreferenceRequest.FromString,
            response_serializer=mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.SetPreferenceResponse.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=mangarr_dot_tachibridge_dot_tachibridge__pb2.HealthCheckRequest.FromString,
            response_serializer=mangarr_dot_tachibridge_dot_tachibridge__pb2.HealthCheckResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "mangarr.tachibridge.Tachibridge", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "mangarr.tachibridge.Tachibridge", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class Tachibridge(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetRepoUrl(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mangarr.tachibridge.Tachibridge/SetRepoUrl",
            mangarr_dot_tachibridge_dot_config_dot_config__pb2.SetRepoUrlRequest.SerializeToString,
            mangarr_dot_tachibridge_dot_config_dot_config__pb2.SetRepoUrlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetFlareSolverrConfig(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mangarr.tachibridge.Tachibridge/GetFlareSolverrConfig",
            mangarr_dot_tachibridge_dot_config_dot_config__pb2.GetFlareSolverrConfigRequest.SerializeToString,
            mangarr_dot_tachibridge_dot_config_dot_config__pb2.GetFlareSolverrConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SetFlareSolverrConfig(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mangarr.tachibridge.Tachibridge/SetFlareSolverrConfig",
            mangarr_dot_tachibridge_dot_config_dot_config__pb2.SetFlareSolverrConfigRequest.SerializeToString,
            mangarr_dot_tachibridge_dot_config_dot_config__pb2.SetFlareSolverrConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def InstallExtension(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mangarr.tachibridge.Tachibridge/InstallExtension",
            mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.InstallExtensionRequest.SerializeToString,
            mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.InstallExtensionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UninstallExtension(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mangarr.tachibridge.Tachibridge/UninstallExtension",
            mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.UninstallExtensionRequest.SerializeToString,
            mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.UninstallExtensionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateExtension(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mangarr.tachibridge.Tachibridge/UpdateExtension",
            mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.UpdateExtensionRequest.SerializeToString,
            mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.InstallExtensionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListRepoExtensions(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mangarr.tachibridge.Tachibridge/ListRepoExtensions",
            mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.ListRepoExtensionsRequest.SerializeToString,
            mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.ListRepoExtensionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListSources(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mangarr.tachibridge.Tachibridge/ListSources",
            mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.ListSourcesRequest.SerializeToString,
            mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.ListSourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SearchTitle(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mangarr.tachibridge.Tachibridge/SearchTitle",
            mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.SearchTitleRequest.SerializeToString,
            mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.TitlesPageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetPopularTitles(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mangarr.tachibridge.Tachibridge/GetPopularTitles",
            mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.GetPopularTitlesRequest.SerializeToString,
            mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.TitlesPageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetLatestTitles(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mangarr.tachibridge.Tachibridge/GetLatestTitles",
            mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.GetLatestTitlesRequest.SerializeToString,
            mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.TitlesPageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetTitleDetails(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mangarr.tachibridge.Tachibridge/GetTitleDetails",
            mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.GetTitleDetailsRequest.SerializeToString,
            mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.TitleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetChapterList(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mangarr.tachibridge.Tachibridge/GetChapterList",
            mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.GetChaptersListRequest.SerializeToString,
            mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.ChaptersListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetPageList(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mangarr.tachibridge.Tachibridge/GetPageList",
            mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.GetPagesListRequest.SerializeToString,
            mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.PagesListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetFilters(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mangarr.tachibridge.Tachibridge/GetFilters",
            mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.GetFiltersRequest.SerializeToString,
            mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.FiltersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SetPreference(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mangarr.tachibridge.Tachibridge/SetPreference",
            mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.SetPreferenceRequest.SerializeToString,
            mangarr_dot_tachibridge_dot_extensions_dot_extensions__pb2.SetPreferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/mangarr.tachibridge.Tachibridge/HealthCheck",
            mangarr_dot_tachibridge_dot_tachibridge__pb2.HealthCheckRequest.SerializeToString,
            mangarr_dot_tachibridge_dot_tachibridge__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
