# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mangarr/tachibridge/config/config.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'mangarr/tachibridge/config/config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'mangarr/tachibridge/config/config.proto\x12\x1amangarr.tachibridge.config\" \n\x11SetRepoUrlRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\"4\n\x12SetRepoUrlResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\xcc\x01\n\x12\x46lareSolverrConfig\x12\x0f\n\x07\x65nabled\x18\x01 \x01(\x08\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x17\n\x0ftimeout_seconds\x18\x03 \x01(\x05\x12\x19\n\x11response_fallback\x18\x04 \x01(\x08\x12\x19\n\x0csession_name\x18\x05 \x01(\tH\x00\x88\x01\x01\x12 \n\x13session_ttl_minutes\x18\x06 \x01(\x05H\x01\x88\x01\x01\x42\x0f\n\r_session_nameB\x16\n\x14_session_ttl_minutes\"\x1e\n\x1cGetFlareSolverrConfigRequest\"_\n\x1dGetFlareSolverrConfigResponse\x12>\n\x06\x63onfig\x18\x01 \x01(\x0b\x32..mangarr.tachibridge.config.FlareSolverrConfig\"^\n\x1cSetFlareSolverrConfigRequest\x12>\n\x06\x63onfig\x18\x01 \x01(\x0b\x32..mangarr.tachibridge.config.FlareSolverrConfig\"?\n\x1dSetFlareSolverrConfigResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\tB!\n\x1amangarr.tachibridge.configP\x01Z\x01.b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mangarr.tachibridge.config.config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032mangarr.tachibridge.configP\001Z\001.'
  _globals['_SETREPOURLREQUEST']._serialized_start=71
  _globals['_SETREPOURLREQUEST']._serialized_end=103
  _globals['_SETREPOURLRESPONSE']._serialized_start=105
  _globals['_SETREPOURLRESPONSE']._serialized_end=157
  _globals['_FLARESOLVERRCONFIG']._serialized_start=160
  _globals['_FLARESOLVERRCONFIG']._serialized_end=364
  _globals['_GETFLARESOLVERRCONFIGREQUEST']._serialized_start=366
  _globals['_GETFLARESOLVERRCONFIGREQUEST']._serialized_end=396
  _globals['_GETFLARESOLVERRCONFIGRESPONSE']._serialized_start=398
  _globals['_GETFLARESOLVERRCONFIGRESPONSE']._serialized_end=493
  _globals['_SETFLARESOLVERRCONFIGREQUEST']._serialized_start=495
  _globals['_SETFLARESOLVERRCONFIGREQUEST']._serialized_end=589
  _globals['_SETFLARESOLVERRCONFIGRESPONSE']._serialized_start=591
  _globals['_SETFLARESOLVERRCONFIGRESPONSE']._serialized_end=654
# @@protoc_insertion_point(module_scope)
